birke_nvc_homepage:
    pattern:  /
    defaults: { _controller: BirkeNvcBundle:Default:index }

birke_nvc_search:
    pattern: /search
    defaults: { _controller: BirkeNvcBundle:Default:search }
    requirements:
            _method:  POST

needs:
    type: rest
    resource: Birke\NvcBundle\Controller\NeedsController