<?php

namespace Birke\NvcBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Need2StrategyConnectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Need2StrategyConnectionRepository extends EntityRepository
{
}
