<?php

namespace Birke\NvcBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * StrategyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrategyRepository extends EntityRepository
{
}
