<?php

namespace Birke\NvcBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * StrategyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrategyRepository extends EntityRepository
{

    /**
     * @param string $name
     * @param int $limit
     * @return mixed
     */
    public function getLikeName($name, $limit=10){
        $qb = $this->createQueryBuilder('s');
        $qb->andWhere($qb->expr()->like('s.name', ':name'))
            ->setMaxResults($limit)
            ->setParameter('name', "%$name%")
        ;
        return $qb->getQuery()->execute();
    }

}
